services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apiusuarios_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Coti@2026"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  adminer:
    image: adminer
    container_name: apiusuarios_adminer_sql
    ports:
      - "8081:8080"

volumes:
  sqlserver_data: